const Type = {
  ADD_RECORD: "ADD_RECORD",
  DELETE_RECORD: "DELETE_RECORD",
  SORT_RECORDS: "SORT_RECORDS",
  GET_RECORDS: "GET_RECORDS",
  LOADER_ON: "LOADER_ON",
  LOADER_OFF: "LOADER_OFF",
};
export default Type;
